stages:
  - build
  - deploy

build-images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -U "$usernameDocker" -p "$passwordDocker"
  script:
    - docker build -t --pull nando2302/backend-express:$CI_COMMIT_SHORT_SHA -f /backend/Dockefile
    - docker push nando2302/backend-express:$CI_COMMIT_SHORT_SHA
    - docker build -t --pull nando2302/frontend-react:$CI_COMMIT_SHORT_SHA -f /backend/Dockerfile
    - docker push nando2302/frontend-react:$CI_COMMIT_SHORT_SHA
  # only: main

deploy-development:
  stage: deploy
  image: alpine
  service:
    - docker:dind
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $HOST_USER@$IP_HOST_DEV "mkdir -p binar"
    - scp -r StrictHostKeyChecking=no docker-compose-development.yml /database/crud_db.sql $HOST_USER@$IP_HOST_DEV:binar
    # - scp -r StrictHostKeyChecking=no ./database/crud_db.sql
    - ssh -o StrictHostKeyChecking=no $HOST_USER@$IP_HOST_PROD
# deploy-production:
