stages:
  - build
  - deploy

build-images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - echo "Build Docker Images For Backend App ..."
    - docker build --pull -t nando2302/backend-express:$CI_COMMIT_SHORT_SHA -f backend/Dockerfile .
    - docker push nando2302/backend-express:$CI_COMMIT_SHORT_SHA
    - echo "Build Docker Images for Frontend App ..."
    - docker build  -f frontend/Dockerfile -t nando2302/frontend-react:$CI_COMMIT_SHORT_SHA .
    - docker push nando2302/frontend-react:$CI_COMMIT_SHORT_SHA
  # only: main

deploy-development:
  stage: deploy
  image: alpine
  services:
    - docker:dind
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEV_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $HOST_USER@$IP_ADDRESS_DEV "mkdir -p binar"
    - scp -o StrictHostKeyChecking=no docker-compose.yml $HOST_USER@$IP_ADDRESS_DEV:binar
    # - scp -r StrictHostKeyChecking=no ./database/crud_db.sql
    - ssh -o StrictHostKeyChecking=no $HOST_USER@$IP_HOST_PROD
# deploy-production:
