version: "3.8"

services:
  backend-app:
    image: nando2302/backend-express:$IMAGE_TAG
    container_name: express-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   - DATABASE_USERNAME=${USER_DB}
    #   - DATABASE_PASSWORD=${PASS_DB}
    #   - DATABASE_DATABASE=${DB_NAME}
    #   - DATABASE_HOST=${HOST_IP}
    #   - DATABASE_PORT=5432
    #   - BASE_URL_PORT=8080
    networks:
      - binar-challange

  frontend-app:
    image: nando2302/frontend-react:$IMAGE_TAG
    container_name: react-frontend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REACT_APP_BACKEND_URL=https://fernando.servercare.id
    networks:
      - binar-challange

networks:
  binar-challange:
    driver: bridge
