version: "3.8"

services:
  backend-app:
    image: nando2302/backend-express:$IMAGE_TAG
    container_name: express-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_USERNAME=binar
      - DATABASE_PASSWORD=binar123
      - DATABASE_DATABASE=people
      - DATABASE_HOST=172.31.177.3
      - DATABASE_PORT=5432
      - BASE_URL_PORT=8080
    networks:
      - binar-challange

  frontend-app:
    image: nando2302/frontend-react:$IMAGE_TAG
    container_name: react-frontend
    ports:
      - "8081:8081"
    environment:
      - REACT_APP_BACKEND_URL=http://IP_ADDRESS:8080
    networks:
      - binar-challange

networks:
  binar-challange:
    driver: bridge
