version: "3.9"

services:
  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=binar123
      - POSTGRES_DB=binar
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql

    networks:
      - backend-to-db

  app-backend:
    image: nando2302/backend-express:$IMAGE_TAG
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=binar123
      - DATABASE_DATABASE=binar
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      - BASE_URL_PORT=8080
    networks:
      - backend-to-db

  frontend-app:
    image: nando2302/frontend-react:$IMAGE_TAG
    ports:
      - "8081:8081"
    environment:
      - REACT_APP_BACKEND_URL=http://$IP_ADDRESS:8080
    networks:
      - backend-to-db

networks:
  backend-to-db:
    driver: bridge

volumes:
  dbdata:
